In [4]:
import pandas as pd

file_path = "/content/drive/MyDrive/project deloit/incident_event_log.csv"

df = pd.read_csv(file_path)

print("Rows:", len(df))
print("Columns:", len(df.columns))
print("\nColumn names:")
print(df.columns.tolist())

Rows: 141712
Columns: 36

Column names:
['number', 'incident_state', 'active', 'reassignment_count', 'reopen_count', 'sys_mod_count', 'made_sla', 'caller_id', 'opened_by', 'opened_at', 'sys_created_by', 'sys_created_at', 'sys_updated_by', 'sys_updated_at', 'contact_type', 'location', 'category', 'subcategory', 'u_symptom', 'cmdb_ci', 'impact', 'urgency', 'priority', 'assignment_group', 'assigned_to', 'knowledge', 'u_priority_confirmation', 'notify', 'problem_id', 'rfc', 'vendor', 'caused_by', 'closed_code', 'resolved_by', 'resolved_at', 'closed_at']

In [2]:
print("Total rows:", len(df))
print("Total columns:", len(df.columns))

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Total rows: 141712
Total columns: 36

Missing values:
number                     0
incident_state             0
active                     0
reassignment_count         0
reopen_count               0
sys_mod_count              0
made_sla                   0
caller_id                  0
opened_by                  0
opened_at                  0
sys_created_by             0
sys_created_at             0
sys_updated_by             0
sys_updated_at             0
contact_type               0
location                   0
category                   0
subcategory                0
u_symptom                  0
cmdb_ci                    0
impact                     0
urgency                    0
priority                   0
assignment_group           0
assigned_to                0
knowledge                  0
u_priority_confirmation    0
notify                     0
problem_id                 0
rfc                        0
vendor                     0
caused_by                  0
closed_code                0
resolved_by                0
resolved_at                0
closed_at                  0
dtype: int64

Duplicate rows: 0

In [5]:
df_quality = df.replace("?", pd.NA)

print("Missing values after recognizing '?':")
print(df_quality.isna().sum().sort_values(ascending=False))

Missing values after recognizing '?':
caused_by                  141689
vendor                     141468
cmdb_ci                    141267
rfc                        140721
problem_id                 139417
sys_created_by              53076
sys_created_at              53076
u_symptom                   32964
assigned_to                 27496
assignment_group            14213
opened_by                    4835
resolved_at                  3141
closed_code                   714
resolved_by                   226
subcategory                   111
category                       78
location                       76
caller_id                      29
incident_state                  0
number                          0
reassignment_count              0
active                          0
contact_type                    0
sys_updated_by                  0
made_sla                        0
sys_mod_count                   0
reopen_count                    0
opened_at                       0
sys_updated_at                  0
u_priority_confirmation         0
notify                          0
priority                        0
impact                          0
urgency                         0
knowledge                       0
closed_at                       0
dtype: int64

In [6]:
print("Unique incidents:", df["number"].nunique())

Unique incidents: 24918

In [7]:
print(df["number"].value_counts().head(10))

number
INC0019396    58
INC0044260    56
INC0005927    46
INC0020718    45
INC0011206    44
INC0025734    43
INC0007349    43
INC0012815    40
INC0003419    38
INC0032450    38
Name: count, dtype: int64

In [9]:
incident = df[df["number"] == "INC0019396"]

print("Number of records:", len(incident))

display(
    incident[
        [
            "number",
            "incident_state",
            "active",
            "reassignment_count",
            "reopen_count",
            "priority",
            "assignment_group",
            "opened_at",
            "sys_updated_at",
            "resolved_at",
            "closed_at"
        ]
    ]
)

Number of records: 58

,number,incident_state,active,reassignment_count,reopen_count,priority,assignment_group,opened_at,sys_updated_at,resolved_at,closed_at
81418,INC0019396,New,True,0,0,3 - Moderate,Group 66,14/4/2016 20:42,14/4/2016 20:42,12/5/2016 23:51,18/5/2016 00:07
81419,INC0019396,New,True,0,0,3 - Moderate,Group 66,14/4/2016 20:42,14/4/2016 21:08,12/5/2016 23:51,18/5/2016 00:07
81420,INC0019396,Resolved,True,0,0,3 - Moderate,Group 66,14/4/2016 20:42,15/4/2016 09:20,12/5/2016 23:51,18/5/2016 00:07
81421,INC0019396,Active,True,0,1,3 - Moderate,Group 66,14/4/2016 20:42,15/4/2016 15:21,12/5/2016 23:51,18/5/2016 00:07
81422,INC0019396,Active,True,0,1,3 - Moderate,Group 66,14/4/2016 20:42,15/4/2016 15:21,12/5/2016 23:51,18/5/2016 00:07
81423,INC0019396,Active,True,0,1,3 - Moderate,Group 66,14/4/2016 20:42,15/4/2016 20:30,12/5/2016 23:51,18/5/2016 00:07
81424,INC0019396,Active,True,0,1,3 - Moderate,Group 66,14/4/2016 20:42,15/4/2016 20:30,12/5/2016 23:51,18/5/2016 00:07
81425,INC0019396,Active,True,0,1,3 - Moderate,Group 66,14/4/2016 20:42,16/4/2016 23:43,12/5/2016 23:51,18/5/2016 00:07
81426,INC0019396,Active,True,0,1,3 - Moderate,Group 66,14/4/2016 20:42,16/4/2016 23:43,12/5/2016 23:51,18/5/2016 00:07
81427,INC0019396,Active,True,1,1,3 - Moderate,Group 54,14/4/2016 20:42,20/4/2016 11:12,12/5/2016 23:51,18/5/2016 00:07
81428,INC0019396,Active,True,2,1,3 - Moderate,Group 20,14/4/2016 20:42,20/4/2016 13:50,12/5/2016 23:51,18/5/2016 00:07
81429,INC0019396,Active,True,3,1,3 - Moderate,Group 66,14/4/2016 20:42,20/4/2016 14:17,12/5/2016 23:51,18/5/2016 00:07
81430,INC0019396,Active,True,4,1,3 - Moderate,Group 54,14/4/2016 20:42,25/4/2016 13:26,12/5/2016 23:51,18/5/2016 00:07
81431,INC0019396,Active,True,4,1,3 - Moderate,Group 54,14/4/2016 20:42,25/4/2016 16:34,12/5/2016 23:51,18/5/2016 00:07
81432,INC0019396,Active,True,5,1,3 - Moderate,Group 66,14/4/2016 20:42,25/4/2016 16:35,12/5/2016 23:51,18/5/2016 00:07
81433,INC0019396,Active,True,6,1,3 - Moderate,Group 20,14/4/2016 20:42,26/4/2016 07:19,12/5/2016 23:51,18/5/2016 00:07
81434,INC0019396,Active,True,7,1,3 - Moderate,Group 66,14/4/2016 20:42,26/4/2016 08:55,12/5/2016 23:51,18/5/2016 00:07
81435,INC0019396,Resolved,True,7,1,3 - Moderate,Group 66,14/4/2016 20:42,27/4/2016 08:55,12/5/2016 23:51,18/5/2016 00:07
81436,INC0019396,Active,True,7,2,3 - Moderate,Group 66,14/4/2016 20:42,30/4/2016 13:34,12/5/2016 23:51,18/5/2016 00:07
81437,INC0019396,Active,True,7,2,3 - Moderate,Group 66,14/4/2016 20:42,30/4/2016 13:34,12/5/2016 23:51,18/5/2016 00:07
81438,INC0019396,Active,True,8,2,3 - Moderate,Group 20,14/4/2016 20:42,1/5/2016 21:02,12/5/2016 23:51,18/5/2016 00:07
81439,INC0019396,Active,True,9,2,3 - Moderate,Group 66,14/4/2016 20:42,2/5/2016 10:22,12/5/2016 23:51,18/5/2016 00:07
81440,INC0019396,Active,True,10,2,3 - Moderate,Group 70,14/4/2016 20:42,2/5/2016 11:13,12/5/2016 23:51,18/5/2016 00:07
81441,INC0019396,Resolved,True,10,2,3 - Moderate,Group 70,14/4/2016 20:42,3/5/2016 11:53,12/5/2016 23:51,18/5/2016 00:07
81442,INC0019396,Active,True,10,3,3 - Moderate,Group 70,14/4/2016 20:42,4/5/2016 23:25,12/5/2016 23:51,18/5/2016 00:07
81443,INC0019396,Active,True,10,3,3 - Moderate,Group 70,14/4/2016 20:42,4/5/2016 23:25,12/5/2016 23:51,18/5/2016 00:07
81444,INC0019396,Active,True,10,3,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 00:19,12/5/2016 23:51,18/5/2016 00:07
81445,INC0019396,Active,True,10,3,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 00:19,12/5/2016 23:51,18/5/2016 00:07
81446,INC0019396,Active,True,10,3,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 00:39,12/5/2016 23:51,18/5/2016 00:07
81447,INC0019396,Active,True,10,3,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 00:39,12/5/2016 23:51,18/5/2016 00:07
81448,INC0019396,Resolved,True,10,3,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 11:11,12/5/2016 23:51,18/5/2016 00:07
81449,INC0019396,Active,True,10,4,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 23:25,12/5/2016 23:51,18/5/2016 00:07
81450,INC0019396,Active,True,10,4,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 23:25,12/5/2016 23:51,18/5/2016 00:07
81451,INC0019396,Active,True,10,4,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 23:51,12/5/2016 23:51,18/5/2016 00:07
81452,INC0019396,Active,True,10,4,3 - Moderate,Group 70,14/4/2016 20:42,5/5/2016 23:51,12/5/2016 23:51,18/5/2016 00:07
81453,INC0019396,Active,True,10,4,3 - Moderate,Group 70,14/4/2016 20:42,6/5/2016 01:29,12/5/2016 23:51,18/5/2016 00:07
81454,INC0019396,Active,True,10,4,3 - Moderate,Group 70,14/4/2016 20:42,6/5/2016 01:29,12/5/2016 23:51,18/5/2016 00:07
81455,INC0019396,Resolved,True,10,4,3 - Moderate,Group 70,14/4/2016 20:42,6/5/2016 14:19,12/5/2016 23:51,18/5/2016 00:07
81456,INC0019396,Active,True,10,5,3 - Moderate,Group 70,14/4/2016 20:42,7/5/2016 06:31,12/5/2016 23:51,18/5/2016 00:07
81457,INC0019396,Active,True,10,5,3 - Moderate,Group 70,14/4/2016 20:42,7/5/2016 06:31,12/5/2016 23:51,18/5/2016 00:07
81458,INC0019396,Active,True,10,5,3 - Moderate,Group 70,14/4/2016 20:42,7/5/2016 07:34,12/5/2016 23:51,18/5/2016 00:07
81459,INC0019396,Active,True,10,5,3 - Moderate,Group 70,14/4/2016 20:42,7/5/2016 07:34,12/5/2016 23:51,18/5/2016 00:07
81460,INC0019396,Active,True,10,5,3 - Moderate,Group 70,14/4/2016 20:42,9/5/2016 12:32,12/5/2016 23:51,18/5/2016 00:07
81461,INC0019396,Awaiting User Info,True,10,5,3 - Moderate,Group 70,14/4/2016 20:42,9/5/2016 12:32,12/5/2016 23:51,18/5/2016 00:07
81462,INC0019396,Resolved,True,10,5,3 - Moderate,Group 70,14/4/2016 20:42,10/5/2016 14:05,12/5/2016 23:51,18/5/2016 00:07
81463,INC0019396,Active,True,10,6,3 - Moderate,Group 70,14/4/2016 20:42,11/5/2016 08:33,12/5/2016 23:51,18/5/2016 00:07
81464,INC0019396,Active,True,10,6,3 - Moderate,Group 70,14/4/2016 20:42,11/5/2016 08:33,12/5/2016 23:51,18/5/2016 00:07
81465,INC0019396,Active,True,10,6,3 - Moderate,Group 70,14/4/2016 20:42,11/5/2016 11:31,12/5/2016 23:51,18/5/2016 00:07
81466,INC0019396,Resolved,True,10,6,3 - Moderate,Group 70,14/4/2016 20:42,11/5/2016 11:31,12/5/2016 23:51,18/5/2016 00:07
81467,INC0019396,Active,True,10,7,3 - Moderate,Group 70,14/4/2016 20:42,12/5/2016 11:53,12/5/2016 23:51,18/5/2016 00:07
81468,INC0019396,Active,True,10,7,3 - Moderate,Group 70,14/4/2016 20:42,12/5/2016 11:53,12/5/2016 23:51,18/5/2016 00:07
81469,INC0019396,Active,True,10,7,3 - Moderate,Group 70,14/4/2016 20:42,12/5/2016 14:32,12/5/2016 23:51,18/5/2016 00:07
81470,INC0019396,Active,True,10,7,3 - Moderate,Group 70,14/4/2016 20:42,12/5/2016 14:46,12/5/2016 23:51,18/5/2016 00:07
81471,INC0019396,Resolved,True,10,7,3 - Moderate,Group 70,14/4/2016 20:42,12/5/2016 14:46,12/5/2016 23:51,18/5/2016 00:07
81472,INC0019396,Active,True,10,8,3 - Moderate,Group 70,14/4/2016 20:42,12/5/2016 16:30,12/5/2016 23:51,18/5/2016 00:07
81473,INC0019396,Active,True,10,8,3 - Moderate,Group 70,14/4/2016 20:42,12/5/2016 16:30,12/5/2016 23:51,18/5/2016 00:07
81474,INC0019396,Resolved,True,10,8,3 - Moderate,Group 70,14/4/2016 20:42,12/5/2016 23:51,12/5/2016 23:51,18/5/2016 00:07
81475,INC0019396,Closed,False,10,8,3 - Moderate,Group 70,14/4/2016 20:42,18/5/2016 00:07,12/5/2016 23:51,18/5/2016 00:07

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141712 entries, 0 to 141711
Data columns (total 36 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   number                   141712 non-null  object
 1   incident_state           141712 non-null  object
 2   active                   141712 non-null  bool
 3   reassignment_count       141712 non-null  int64
 4   reopen_count             141712 non-null  int64
 5   sys_mod_count            141712 non-null  int64
 6   made_sla                 141712 non-null  bool
 7   caller_id                141712 non-null  object
 8   opened_by                141712 non-null  object
 9   opened_at                141712 non-null  object
 10  sys_created_by           141712 non-null  object
 11  sys_created_at           141712 non-null  object
 12  sys_updated_by           141712 non-null  object
 13  sys_updated_at           141712 non-null  object
 14  contact_type             141712 non-null  object
 15  location                 141712 non-null  object
 16  category                 141712 non-null  object
 17  subcategory              141712 non-null  object
 18  u_symptom                141712 non-null  object
 19  cmdb_ci                  141712 non-null  object
 20  impact                   141712 non-null  object
 21  urgency                  141712 non-null  object
 22  priority                 141712 non-null  object
 23  assignment_group         141712 non-null  object
 24  assigned_to              141712 non-null  object
 25  knowledge                141712 non-null  bool
 26  u_priority_confirmation  141712 non-null  bool
 27  notify                   141712 non-null  object
 28  problem_id               141712 non-null  object
 29  rfc                      141712 non-null  object
 30  vendor                   141712 non-null  object
 31  caused_by                141712 non-null  object
 32  closed_code              141712 non-null  object
 33  resolved_by              141712 non-null  object
 34  resolved_at              141712 non-null  object
 35  closed_at                141712 non-null  object
dtypes: bool(4), int64(3), object(29)
memory usage: 35.1+ MB

In [11]:
date_cols = [
    "opened_at",
    "sys_created_at",
    "sys_updated_at",
    "resolved_at",
    "closed_at"
]

for col in date_cols:
    print(col, "→", (df[col] == "?").sum(), "unknown values")

opened_at → 0 unknown values
sys_created_at → 53076 unknown values
sys_updated_at → 0 unknown values
resolved_at → 3141 unknown values
closed_at → 0 unknown values

In [12]:
date_cols = [
    "opened_at",
    "sys_created_at",
    "sys_updated_at",
    "resolved_at",
    "closed_at"
]

for col in date_cols:
    df[col] = pd.to_datetime(
        df[col].replace("?", pd.NaT),
        dayfirst=True,
        errors="coerce"
    )

df[date_cols].dtypes

opened_at         datetime64[ns]
sys_created_at    datetime64[ns]
sys_updated_at    datetime64[ns]
resolved_at       datetime64[ns]
closed_at         datetime64[ns]
dtype: object

In [14]:
df[date_cols].isna().sum()

opened_at             0
sys_created_at    53076
sys_updated_at        0
resolved_at        3141
closed_at             0
dtype: int64

In [15]:
categorical_cols = [
    "incident_state",
    "contact_type",
    "location",
    "category",
    "subcategory",
    "impact",
    "urgency",
    "priority",
    "assignment_group"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print("Unique values:", df[col].nunique())
    print(df[col].value_counts().head(10))

--- incident_state ---
Unique values: 9
incident_state
Active                38716
New                   36407
Resolved              25751
Closed                24985
Awaiting User Info    14642
Awaiting Vendor         707
Awaiting Problem        461
Awaiting Evidence        38
-100                      5
Name: count, dtype: int64

--- contact_type ---
Unique values: 5
contact_type
Phone             140462
Self service         995
Email                220
IVR                   18
Direct opening        17
Name: count, dtype: int64

--- location ---
Unique values: 225
location
Location 204    31690
Location 161    22605
Location 143    19245
Location 108    12623
Location 93     11554
Location 51      8016
Location 188     2142
Location 179     1975
Location 43      1748
Location 111     1530
Name: count, dtype: int64

--- category ---
Unique values: 59
category
Category 26    18453
Category 42    15977
Category 53    15968
Category 46    13324
Category 23     7779
Category 9      7365
Category 32     7273
Category 37     6584
Category 57     6532
Category 20     5506
Name: count, dtype: int64

--- subcategory ---
Unique values: 255
subcategory
Subcategory 174    35785
Subcategory 223    15598
Subcategory 175    10496
Subcategory 164     7880
Subcategory 9       4124
Subcategory 275     3643
Subcategory 135     3467
Subcategory 170     3349
Subcategory 36      2917
Subcategory 75      2113
Name: count, dtype: int64

--- impact ---
Unique values: 3
impact
2 - Medium    134335
3 - Low         3886
1 - High        3491
Name: count, dtype: int64

--- urgency ---
Unique values: 3
urgency
2 - Medium    134094
1 - High        4020
3 - Low         3598
Name: count, dtype: int64

--- priority ---
Unique values: 4
priority
3 - Moderate    132452
4 - Low           4030
2 - High          2972
1 - Critical      2258
Name: count, dtype: int64

--- assignment_group ---
Unique values: 79
assignment_group
Group 70    43474
?           14213
Group 25     7679
Group 24     6752
Group 20     6170
Group 39     4728
Group 23     4228
Group 27     3817
Group 28     3638
Group 73     3304
Name: count, dtype: int64

In [16]:
df[
    ["reassignment_count", "reopen_count", "sys_mod_count"]
].describe()

       reassignment_count   reopen_count  sys_mod_count
count       141712.000000  141712.000000  141712.000000
mean             1.104197       0.021918       5.080946
std              1.734673       0.207302       7.680652
min              0.000000       0.000000       0.000000
25%              0.000000       0.000000       1.000000
50%              1.000000       0.000000       3.000000
75%              1.000000       0.000000       6.000000
max             27.000000       8.000000     129.000000

In [17]:
boolean_cols = [
    "active",
    "made_sla",
    "knowledge",
    "u_priority_confirmation"
]

for col in boolean_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- active ---
active
True     116726
False     24986
Name: count, dtype: int64

--- made_sla ---
made_sla
True     132497
False      9215
Name: count, dtype: int64

--- knowledge ---
knowledge
False    116349
True      25363
Name: count, dtype: int64

--- u_priority_confirmation ---
u_priority_confirmation
False    100740
True      40972
Name: count, dtype: int64

In [18]:
question_counts = (df == "?").sum().sort_values(ascending=False)

question_counts[question_counts > 0]

caused_by           141689
vendor              141468
cmdb_ci             141267
rfc                 140721
problem_id          139417
sys_created_by       53076
u_symptom            32964
assigned_to          27496
assignment_group     14213
opened_by             4835
closed_code            714
resolved_by            226
subcategory            111
category                78
location                76
caller_id               29
dtype: int64

In [19]:
missing_summary = pd.DataFrame({
    "missing_count": (df == "?").sum(),
    "missing_percent": ((df == "?").sum() / len(df) * 100).round(2)
})

missing_summary = missing_summary[
    missing_summary["missing_count"] > 0
].sort_values("missing_percent", ascending=False)

display(missing_summary)

                  missing_count  missing_percent
caused_by                141689            99.98
vendor                   141468            99.83
cmdb_ci                  141267            99.69
rfc                      140721            99.30
problem_id               139417            98.38
sys_created_by            53076            37.45
u_symptom                 32964            23.26
assigned_to               27496            19.40
assignment_group          14213            10.03
opened_by                  4835             3.41
closed_code                 714             0.50
resolved_by                 226             0.16
subcategory                 111             0.08
category                     78             0.06
location                     76             0.05
caller_id                    29             0.02

In [20]:
drop_cols = [
    "caused_by",
    "vendor",
    "cmdb_ci",
    "rfc",
    "problem_id",
    "sys_created_by",
    "u_symptom"
]

df_clean = df.drop(columns=drop_cols)

print("Original columns:", len(df.columns))
print("Cleaned columns:", len(df_clean.columns))
print("\nRemaining columns:")
print(df_clean.columns.tolist())

Original columns: 36
Cleaned columns: 29

Remaining columns:
['number', 'incident_state', 'active', 'reassignment_count', 'reopen_count', 'sys_mod_count', 'made_sla', 'caller_id', 'opened_by', 'opened_at', 'sys_created_at', 'sys_updated_by', 'sys_updated_at', 'contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assignment_group', 'assigned_to', 'knowledge', 'u_priority_confirmation', 'notify', 'closed_code', 'resolved_by', 'resolved_at', 'closed_at']

In [21]:
missing_clean = (df_clean == "?").sum().sort_values(ascending=False)

missing_clean[missing_clean > 0]

assigned_to         27496
assignment_group    14213
opened_by            4835
closed_code           714
resolved_by           226
subcategory           111
category               78
location               76
caller_id              29
dtype: int64

In [22]:
fill_values = {
    "assigned_to": "Unassigned",
    "assignment_group": "Unassigned",
    "opened_by": "Unknown",
    "closed_code": "Unknown",
    "resolved_by": "Unknown",
    "subcategory": "Unknown",
    "category": "Unknown",
    "location": "Unknown",
    "caller_id": "Unknown"
}

df_clean = df_clean.replace("?", pd.NA)
df_clean = df_clean.fillna(fill_values)

print("Remaining missing values:")
print(df_clean.isna().sum()[df_clean.isna().sum() > 0])

Remaining missing values:
sys_created_at    53076
resolved_at        3141
dtype: int64

In [23]:
incident = df_clean[df_clean["number"] == "INC0019396"]

print("Number of records:", len(incident))

display(
    incident[
        [
            "number",
            "incident_state",
            "active",
            "reassignment_count",
            "reopen_count",
            "priority",
            "assignment_group",
            "opened_at",
            "sys_updated_at",
            "resolved_at",
            "closed_at"
        ]
    ].tail()
)

Number of records: 58

,number,incident_state,active,reassignment_count,reopen_count,priority,assignment_group,opened_at,sys_updated_at,resolved_at,closed_at
81471,INC0019396,Resolved,True,10,7,3 - Moderate,Group 70,2016-04-14 20:42:00,2016-05-12 14:46:00,2016-05-12 23:51:00,2016-05-18 00:07:00
81472,INC0019396,Active,True,10,8,3 - Moderate,Group 70,2016-04-14 20:42:00,2016-05-12 16:30:00,2016-05-12 23:51:00,2016-05-18 00:07:00
81473,INC0019396,Active,True,10,8,3 - Moderate,Group 70,2016-04-14 20:42:00,2016-05-12 16:30:00,2016-05-12 23:51:00,2016-05-18 00:07:00
81474,INC0019396,Resolved,True,10,8,3 - Moderate,Group 70,2016-04-14 20:42:00,2016-05-12 23:51:00,2016-05-12 23:51:00,2016-05-18 00:07:00
81475,INC0019396,Closed,False,10,8,3 - Moderate,Group 70,2016-04-14 20:42:00,2016-05-18 00:07:00,2016-05-12 23:51:00,2016-05-18 00:07:00

In [24]:
df_clean = df_clean.sort_values(
    ["number", "sys_updated_at"]
).reset_index(drop=True)

print(df_clean[["number", "sys_updated_at"]].head())

       number      sys_updated_at
0  INC0000045 2016-02-29 01:23:00
1  INC0000045 2016-02-29 08:53:00
2  INC0000045 2016-02-29 11:29:00
3  INC0000045 2016-03-05 12:00:00
4  INC0000047 2016-02-29 04:57:00

In [25]:
check_cols = [
    "priority",
    "impact",
    "urgency",
    "category",
    "subcategory",
    "assignment_group"
]

for col in check_cols:
    changes = df_clean.groupby("number")[col].nunique()
    print(f"{col}:")
    print("  Incidents with changes:", (changes > 1).sum())
    print("  Maximum different values in one incident:", changes.max())

priority:
  Incidents with changes: 383
  Maximum different values in one incident: 3
impact:
  Incidents with changes: 315
  Maximum different values in one incident: 3
urgency:
  Incidents with changes: 299
  Maximum different values in one incident: 3
category:
  Incidents with changes: 1216
  Maximum different values in one incident: 4
subcategory:
  Incidents with changes: 1799
  Maximum different values in one incident: 5
assignment_group:
  Incidents with changes: 11344
  Maximum different values in one incident: 9

In [26]:
incident_df = df_clean.groupby("number").agg(
    opened_at=("opened_at", "first"),
    resolved_at=("resolved_at", "last"),
    closed_at=("closed_at", "last"),

    final_state=("incident_state", "last"),
    final_active=("active", "last"),

    reassignment_count=("reassignment_count", "last"),
    reopen_count=("reopen_count", "last"),
    sys_mod_count=("sys_mod_count", "last"),

    made_sla=("made_sla", "last"),

    priority=("priority", "last"),
    impact=("impact", "last"),
    urgency=("urgency", "last"),

    category=("category", "last"),
    subcategory=("subcategory", "last"),

    assignment_group=("assignment_group", "last"),
    assigned_to=("assigned_to", "last"),

    location=("location", "last"),
    contact_type=("contact_type", "first"),

    knowledge=("knowledge", "last"),
    u_priority_confirmation=("u_priority_confirmation", "last"),

    closed_code=("closed_code", "last"),
    resolved_by=("resolved_by", "last")
).reset_index()

print("Event records:", len(df_clean))
print("Unique incidents:", len(incident_df))

display(incident_df.head())

Event records: 141712
Unique incidents: 24918

,number,opened_at,resolved_at,closed_at,final_state,final_active,reassignment_count,reopen_count,sys_mod_count,made_sla,...,category,subcategory,assignment_group,assigned_to,location,contact_type,knowledge,u_priority_confirmation,closed_code,resolved_by
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2016-03-05 12:00:00,Closed,False,0,0,4,True,...,Category 55,Subcategory 170,Group 56,Unassigned,Location 143,Phone,True,False,code 5,Resolved by 149
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2016-03-06 10:00:00,Closed,False,1,0,8,True,...,Category 40,Subcategory 215,Group 24,Resolver 89,Location 165,Phone,True,False,code 5,Resolved by 81
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2016-03-06 03:00:00,Closed,False,0,0,6,True,...,Category 20,Subcategory 125,Group 70,Resolver 6,Location 204,Phone,True,False,code 10,Resolved by 5
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2016-03-07 13:00:00,Closed,False,0,0,3,True,...,Category 9,Subcategory 97,Group 25,Resolver 125,Location 204,Phone,True,False,code 3,Resolved by 113
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2016-03-05 16:00:00,Closed,False,1,0,7,False,...,Category 53,Subcategory 168,Group 23,Unassigned,Location 93,Phone,True,False,code 7,Resolved by 62

In [27]:
incident_df["resolution_time_hours"] = (
    incident_df["resolved_at"] - incident_df["opened_at"]
).dt.total_seconds() / 3600

incident_df["closure_time_hours"] = (
    incident_df["closed_at"] - incident_df["opened_at"]
).dt.total_seconds() / 3600

display(
    incident_df[
        [
            "number",
            "opened_at",
            "resolved_at",
            "closed_at",
            "resolution_time_hours",
            "closure_time_hours"
        ]
    ].head()
)

,number,opened_at,resolved_at,closed_at,resolution_time_hours,closure_time_hours
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2016-03-05 12:00:00,10.216667,130.733333
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2016-03-06 10:00:00,29.200000,149.333333
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2016-03-06 03:00:00,20.750000,140.833333
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2016-03-07 13:00:00,53.466667,174.366667
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2016-03-05 16:00:00,8.883333,129.033333

In [28]:
print("Negative resolution times:", (incident_df["resolution_time_hours"] < 0).sum())
print("Negative closure times:", (incident_df["closure_time_hours"] < 0).sum())

print("Missing resolution times:", incident_df["resolution_time_hours"].isna().sum())
print("Missing closure times:", incident_df["closure_time_hours"].isna().sum())

Negative resolution times: 0
Negative closure times: 0
Missing resolution times: 1556
Missing closure times: 0

In [29]:
display(
    incident_df[
        ["resolution_time_hours", "closure_time_hours"]
    ].describe()
)

       resolution_time_hours  closure_time_hours
count           23362.000000        24918.000000
mean              178.171582          315.328634
std               532.787772          533.175088
min                 0.000000            0.000000
25%                 0.416667          120.983333
50%                22.100000          145.866667
75%               148.479167          319.658333
max              8070.166667         8190.616667

In [30]:
incident_df["is_reopened"] = incident_df["reopen_count"] > 0

incident_df["is_reassigned"] = incident_df["reassignment_count"] > 0

incident_df["sla_breached"] = incident_df["made_sla"] == False

incident_df["resolution_time_days"] = (
    incident_df["resolution_time_hours"] / 24
)

display(
    incident_df[
        [
            "number",
            "reopen_count",
            "is_reopened",
            "reassignment_count",
            "is_reassigned",
            "made_sla",
            "sla_breached",
            "resolution_time_days"
        ]
    ].head()
)

,number,reopen_count,is_reopened,reassignment_count,is_reassigned,made_sla,sla_breached,resolution_time_days
0,INC0000045,0,False,0,False,True,False,0.425694
1,INC0000047,0,False,1,True,True,False,1.216667
2,INC0000057,0,False,0,False,True,False,0.864583
3,INC0000060,0,False,0,False,True,False,2.227778
4,INC0000062,0,False,1,True,False,True,0.370139

In [31]:
sla_summary = incident_df["made_sla"].value_counts()

print("SLA Met:", sla_summary.get(True, 0))
print("SLA Not Met:", sla_summary.get(False, 0))

print(
    "SLA Compliance Rate:",
    round(incident_df["made_sla"].mean() * 100, 2),
    "%"
)

print(
    "SLA Breach Rate:",
    round(incident_df["sla_breached"].mean() * 100, 2),
    "%"
)

SLA Met: 15803
SLA Not Met: 9115
SLA Compliance Rate: 63.42 %
SLA Breach Rate: 36.58 %

In [32]:
team_sla = (
    incident_df
    .groupby("assignment_group")
    .agg(
        total_incidents=("number", "count"),
        sla_breaches=("sla_breached", "sum")
    )
    .reset_index()
)

team_sla["sla_breach_rate"] = (
    team_sla["sla_breaches"] /
    team_sla["total_incidents"] * 100
)

team_sla = team_sla.sort_values(
    "sla_breach_rate",
    ascending=False
)

display(team_sla.head(15))

   assignment_group  total_incidents  sla_breaches  sla_breach_rate
3          Group 14               13            13       100.000000
6          Group 18                2             2       100.000000
58          Group 7                1             1       100.000000
66         Group 77                1             1       100.000000
68         Group 80                1             1       100.000000
60         Group 71                2             2       100.000000
4          Group 15               58            57        98.275862
69          Group 9               96            94        97.916667
64         Group 75               60            57        95.000000
25         Group 35               17            16        94.117647
5          Group 17               11            10        90.909091
15         Group 26               24            21        87.500000
1          Group 12              123           107        86.991870
49         Group 61               38            33        86.842105
51         Group 63                7             6        85.714286

In [33]:
team_sla_50 = team_sla[
    team_sla["total_incidents"] >= 50
].sort_values(
    "sla_breach_rate",
    ascending=False
)

display(team_sla_50)

   assignment_group  total_incidents  sla_breaches  sla_breach_rate
4          Group 15               58            57        98.275862
69          Group 9               96            94        97.916667
64         Group 75               60            57        95.000000
1          Group 12              123           107        86.991870
19          Group 3               99            82        82.828283
27         Group 37              176           132        75.000000
0          Group 10              343           257        74.927114
38         Group 50               51            38        74.509804
54         Group 66              376           262        69.680851
63         Group 74              105            73        69.523810
21         Group 31              205           140        68.292683
44         Group 57              313           213        68.051118
61         Group 72              367           232        63.215259
18         Group 29              257           160        62.256809
23         Group 33              201           123        61.194030
10         Group 21               58            35        60.344828
9          Group 20              394           230        58.375635
65         Group 76              189           110        58.201058
14         Group 25             1243           711        57.200322
53         Group 65              336           190        56.547619
47          Group 6              257           143        55.642023
11         Group 22              239           130        54.393305
41         Group 54              200           106        53.000000
37          Group 5              140            73        52.142857
70       Unassigned             2157          1108        51.367640
35         Group 48              162            81        50.000000
40         Group 53               93            45        48.387097
17         Group 28              545           253        46.422018
62         Group 73              576           265        46.006944
16         Group 27              518           216        41.698842
12         Group 23              811           335        41.307028
43         Group 56              167            66        39.520958
42         Group 55              293           114        38.907850
20         Group 30              268           100        37.313433
45         Group 58              142            50        35.211268
13         Group 24             1060           373        35.188679
57         Group 69               73            25        34.246575
28         Group 39             1199           374        31.192661
33         Group 46              166            49        29.518072
24         Group 34               51            14        27.450980
36         Group 49              108            27        25.000000
59         Group 70             9444          1526        16.158407
52         Group 64              716            78        10.893855

In [34]:
priority_sla = (
    incident_df
    .groupby("priority")
    .agg(
        total_incidents=("number", "count"),
        sla_breaches=("sla_breached", "sum")
    )
    .reset_index()
)

priority_sla["sla_breach_rate"] = (
    priority_sla["sla_breaches"] /
    priority_sla["total_incidents"] * 100
)

display(
    priority_sla.sort_values("priority")
)

       priority  total_incidents  sla_breaches  sla_breach_rate
0  1 - Critical              270           265        98.148148
1      2 - High              408           406        99.509804
2  3 - Moderate            23466          8321        35.459814
3       4 - Low              774           123        15.891473

In [35]:
priority_resolution = (
    incident_df
    .groupby("priority")
    .agg(
        total_incidents=("number", "count"),
        avg_resolution_hours=("resolution_time_hours", "mean"),
        median_resolution_hours=("resolution_time_hours", "median"),
        avg_closure_hours=("closure_time_hours", "mean")
    )
    .reset_index()
)

display(
    priority_resolution.sort_values("priority")
)

,priority,total_incidents,avg_resolution_hours,median_resolution_hours,avg_closure_hours
0,1 - Critical,270,266.084012,80.241667,397.700802
1,2 - High,408,152.456618,38.233333,296.402451
2,3 - Moderate,23466,174.354043,21.550000,311.895638
3,4 - Low,774,283.185509,5.016667,400.651723

In [36]:
category_sla = (
    incident_df
    .groupby("category")
    .agg(
        total_incidents=("number", "count"),
        sla_breaches=("sla_breached", "sum"),
        median_resolution_hours=("resolution_time_hours", "median")
    )
    .reset_index()
)

category_sla["sla_breach_rate"] = (
    category_sla["sla_breaches"] /
    category_sla["total_incidents"] * 100
)

category_sla = category_sla[
    category_sla["total_incidents"] >= 100
].sort_values(
    "sla_breach_rate",
    ascending=False
)

display(category_sla)

,category,total_incidents,sla_breaches,median_resolution_hours,sla_breach_rate
40,Category 55,106,84,169.325000,79.245283
30,Category 45,602,446,147.733333,74.086379
21,Category 34,501,333,404.716667,66.467066
26,Category 40,436,266,73.083333,61.009174
6,Category 19,245,130,61.116667,53.061224
46,Category 61,810,429,95.383333,52.962963
31,Category 46,2432,1254,65.708333,51.562500
29,Category 44,302,151,25.566667,50.000000
11,Category 23,1063,505,46.300000,47.507056
12,Category 24,640,303,72.216667,47.343750
51,Category 9,1155,471,45.766667,40.779221
42,Category 57,971,390,42.583333,40.164779
2,Category 13,126,50,50.283333,39.682540
28,Category 43,153,59,19.258333,38.562092
38,Category 53,2678,1009,27.883333,37.677371
23,Category 37,1144,385,22.550000,33.653846
14,Category 26,3338,1017,5.583333,30.467346
15,Category 28,551,160,0.183333,29.038113
19,Category 32,1522,377,1.141667,24.770039
8,Category 20,1047,241,1.900000,23.018147
36,Category 51,549,109,0.200000,19.854281
27,Category 42,3558,689,0.633333,19.364812
22,Category 35,517,46,0.250000,8.897485

In [37]:
reassignment_sla = (
    incident_df
    .groupby("is_reassigned")
    .agg(
        total_incidents=("number", "count"),
        sla_breaches=("sla_breached", "sum"),
        median_resolution_hours=("resolution_time_hours", "median")
    )
    .reset_index()
)

reassignment_sla["sla_breach_rate"] = (
    reassignment_sla["sla_breaches"] /
    reassignment_sla["total_incidents"] * 100
)

display(reassignment_sla)

,is_reassigned,total_incidents,sla_breaches,median_resolution_hours,sla_breach_rate
0,False,13549,2928,0.683333,21.610451
1,True,11369,6187,79.933333,54.419914

In [38]:
reopen_sla = (
    incident_df
    .groupby("is_reopened")
    .agg(
        total_incidents=("number", "count"),
        sla_breaches=("sla_breached", "sum"),
        median_resolution_hours=("resolution_time_hours", "median")
    )
    .reset_index()
)

reopen_sla["sla_breach_rate"] = (
    reopen_sla["sla_breaches"] /
    reopen_sla["total_incidents"] * 100
)

display(reopen_sla)

,is_reopened,total_incidents,sla_breaches,median_resolution_hours,sla_breach_rate
0,False,24643,8907,21.241667,36.144138
1,True,275,208,236.583333,75.636364

In [39]:
reassignment_analysis = (
    incident_df
    .groupby("reassignment_count")
    .agg(
        total_incidents=("number", "count"),
        sla_breaches=("sla_breached", "sum"),
        median_resolution_hours=("resolution_time_hours", "median")
    )
    .reset_index()
)

reassignment_analysis["sla_breach_rate"] = (
    reassignment_analysis["sla_breaches"] /
    reassignment_analysis["total_incidents"] * 100
)

display(reassignment_analysis.head(15))

,reassignment_count,total_incidents,sla_breaches,median_resolution_hours,sla_breach_rate
0,0,13549,2928,0.683333,21.610451
1,1,6238,2678,42.050000,42.930426
2,2,2283,1373,102.966667,60.140166
3,3,1234,828,146.100000,67.098865
4,4,695,520,186.100000,74.820144
5,5,381,296,208.466667,77.690289
6,6,183,157,283.666667,85.792350
7,7,143,131,315.733333,91.608392
8,8,70,65,357.791667,92.857143
9,9,52,51,336.458333,98.076923
10,10,31,31,477.283333,100.000000
11,11,18,17,504.508333,94.444444
12,12,17,16,485.816667,94.117647
13,13,7,7,457.600000,100.000000
14,14,5,5,598.900000,100.000000

In [40]:
state_analysis = (
    incident_df
    .groupby("final_state")
    .agg(
        total_incidents=("number", "count"),
        sla_breaches=("sla_breached", "sum"),
        median_resolution_hours=("resolution_time_hours", "median")
    )
    .reset_index()
)

state_analysis["sla_breach_rate"] = (
    state_analysis["sla_breaches"] /
    state_analysis["total_incidents"] * 100
)

display(
    state_analysis.sort_values(
        "total_incidents",
        ascending=False
    )
)

,final_state,total_incidents,sla_breaches,median_resolution_hours,sla_breach_rate
0,Closed,24918,9115,22.1,36.579982

In [41]:
incident_df["opened_month"] = (
    incident_df["opened_at"]
    .dt.to_period("M")
    .astype(str)
)

monthly_volume = (
    incident_df
    .groupby("opened_month")
    .agg(
        total_incidents=("number", "count"),
        sla_breaches=("sla_breached", "sum"),
        median_resolution_hours=("resolution_time_hours", "median")
    )
    .reset_index()
)

monthly_volume["sla_breach_rate"] = (
    monthly_volume["sla_breaches"] /
    monthly_volume["total_incidents"] * 100
)

display(monthly_volume)

,opened_month,total_incidents,sla_breaches,median_resolution_hours,sla_breach_rate
0,2016-02,207,73,53.791667,35.265700
1,2016-03,8995,5410,71.183333,60.144525
2,2016-04,7934,1849,4.333333,23.304764
3,2016-05,7508,1688,2.900000,22.482685
4,2016-06,5,1,26.650000,20.000000
5,2016-07,14,3,34.791667,21.428571
6,2016-08,15,8,145.183333,53.333333
7,2016-09,12,5,64.450000,41.666667
8,2016-10,16,9,110.975000,56.250000
9,2016-11,26,9,1.141667,34.615385
10,2016-12,37,14,43.916667,37.837838
11,2017-01,94,41,57.100000,43.617021
12,2017-02,55,5,2.866667,9.090909

In [42]:
incident_df.to_csv(
    "/content/incident_level_clean.csv",
    index=False
)

In [43]:
print(incident_df.shape)
print(incident_df.columns.tolist())

(24918, 30)
['number', 'opened_at', 'resolved_at', 'closed_at', 'final_state', 'final_active', 'reassignment_count', 'reopen_count', 'sys_mod_count', 'made_sla', 'priority', 'impact', 'urgency', 'category', 'subcategory', 'assignment_group', 'assigned_to', 'location', 'contact_type', 'knowledge', 'u_priority_confirmation', 'closed_code', 'resolved_by', 'resolution_time_hours', 'closure_time_hours', 'is_reopened', 'is_reassigned', 'sla_breached', 'resolution_time_days', 'opened_month']